### ISSUE TITLE
"No result found"

### ISSUE THREAD

**Issue by dhyanKaro** [c-eg/ShowRenamer#77]
Clicking on Get Suggestions results in
```
$> java -jar show-renamer-1.3.0.jar
Nov 25, 2023 12:09:28 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ced7109'
[JavaFX Application Thread] INFO uk.co.conoregan.showrenamer.ShowRenamerApplication - Show Renamer successfully started.
[ForkJoinPool.commonPool-worker-2] INFO uk.co.conoregan.showrenamer.suggestion.FileSuggestionProvider - No result found for title: <my title>
```
Not sure if I installed the prerequisite JDK properly. Maybe the app could detect it and if it's not there give some kind of notice.

**Comment by c-eg** [comment]
Hi, the installed JDK is not an issue - the app wouldn't open if it was.

Please could you provide the name of the show you wanted to rename, as well as the file name (you can omit the extension if you'd like).

The file name format has the potential to not match correctly. I tried to cover all common file name variations but of course, I could have missed one.

There is also a chance that this show does not exist on [The Movie Database](https://www.themoviedb.org/?language=en-GB). Could you search for it there to make sure it exists?
